on:
    push:
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - run: shopt -s globstar
            - uses: actions/checkout@v4
            - uses: DavidAnson/markdownlint-cli2-action@v13
              with:
                  globs: "**/*.md"

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/configure-pages@v5
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - run: pip install mkslides
            - run: mkslides build docs/slides.md
            - uses: actions/upload-pages-artifact@v3
              with:
                path: ./site
            - id: deployment
              uses: actions/deploy-pages@v4
